# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.5.0
_src_path: gh:hugoh/go-tools
codecov_ignore:
- internal/version
codecov_style: simple
cog_omit_types:
- lint
coverage_total: 80
dev_watch: false
golangci_extra_disable:
- depguard
- exhaustruct
- godoclint
- testpackage
golangci_extra_exclusions: []
golangci_settings: ''
golangci_test_exclude_linters:
- err113
- noctx
- varnamelen
goreleaser_before_hooks: []
goreleaser_version_pkg: github.com/hugoh/upd/internal/version
has_fuzz: false
has_gen: false
has_goreleaser: true
has_homebrew_cask: false
has_test_int: true
hk_has_golangci_step: true
hk_has_goreleaser_step: false
hk_prepush_with_go_ci: false
nfpm_extra_contents: []
project_description: Tool to monitor if the network connection is up
project_name: upd
test_int_cmd: gotestsum -- -race -tags=integration ./...
testcoverage_excludes: []
testcoverage_overrides: []

