---
issues:
  exclude-files:
    - _test\.go
linters:
  enable-all: true
  disable:
    - depguard
    - godot
    - nlreturn
    - varnamelen
    - wsl
linters-settings:
  errcheck:
    check-blank: true
