version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - godoclint
    - godot
    - nlreturn
    - wsl
    - wsl_v5
  settings:
    errcheck:
      check-blank: true
  exclusions:
    generated: lax
    presets:
      - comments
    paths:
      - _test\.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - _test\.go
      - third_party$
      - builtin$
      - examples$
