version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: "386"
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w
      - -X github.com/hugoh/upd/internal/version.version={{.Version}}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - maintainer: "Hugo Haas <hugoh@hugoh.net>"
    description: "Tool to monitor if the network connection is up"
    homepage: "https://github.com/hugoh/upd"
    license: "MIT"
    formats:
      - deb
      - rpm
    bindir: /usr/bin

changelog:
  use: git
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^chore\\(release\\): prepare for"
      - "^chore\\(deps"

checksum:
  name_template: "checksums.txt"

snapshot:
