[tools]
go = "1.26.4"
"go:github.com/vladopajic/go-test-coverage/v2" = "2.18.8"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.4.0"
golangci-lint = "2.12.2"
goreleaser = "2.16.0"
cocogitto = "7.0.0"
gotestsum = "1.13.0"
hk = "1.48.0"
rumdl = "0.2.22"
zizmor = "1.26.1"
dprint = "0.54.0"
ghalint = "1.5.6"
gitleaks = "8.30.1"
actionlint = "1.7.12"
copier = "9.16.0"
"npm:cpd" = "5.0.11"
"go:golang.org/x/tools/cmd/deadcode" = "0.46.0"

[env]
COVEROUT = "cover.out"
HK_PKL_BACKEND = "pklr"

[settings]
task.timings = false
