version: "3"

vars:
  STATICDIR: internal/status/static
  COVEROUT: cover.out
  FUNCSOUT: funcs-{{.COVEROUT}}
  GOBIN: $(go env GOPATH)/bin
  TEST_COVERAGE: 80

tasks:
  default:
    deps: [dev]

  coverage:
    summary: Generate test coverage
    cmds:
      - task: test
        vars:
          CLI_ARGS: -coverprofile={{.COVEROUT}} -covermode=atomic -coverpkg=./...
    sources:
      - "**/*.go"
    generates:
      - "{{.COVEROUT}}"

  coverfunc:
    summary: Generate test coverage function
    deps:
      - coverage
    cmd: go tool cover -func={{.COVEROUT}} > {{.FUNCSOUT}}
    sources:
      - "{{.COVEROUT}}"
    generates:
      - "{{.FUNCSOUT}}"

  covercheck:
    summary: Check test coverage
    deps:
      - coverfunc
    cmds:
      - cat {{.FUNCSOUT}}
      - |
        awk '/total/{gsub(/%/,"",$3); print "Coverage: " $3 "% (Minimum: {{.TEST_COVERAGE}}%)"; if ($3 < {{.TEST_COVERAGE}}) exit 1}' < "{{.FUNCSOUT}}"

  dev:
    summary: Development mode
    cmd: go run . {{.CLI_ARGS}}

  build:
    summary: Build application
    cmd: go build -o dist/upd .

  clean:
    summary: Clean the project
    cmds:
      - go clean
      - rm -f {{.COVEROUT}}

  fixlint:
    summary: Fix lint issues
    cmd: go tool github.com/golangci/golangci-lint/v2/cmd/golangci-lint run --fix ./...

  fmt:
    summary: Format the code
    cmd: go tool github.com/golangci/golangci-lint/v2/cmd/golangci-lint run --fix ./...

  tidy:
    summary: Tidy the module
    cmd: go mod tidy -v

  depup:
    summary: Upgrades dependencies
    cmds:
      - go get -u -t ./...
      - task: tidy

  lint:
    summary: Lint code
    cmds:
      - go mod tidy -diff
      - go tool github.com/golangci/golangci-lint/v2/cmd/golangci-lint run ./...

  ci:
    summary: Run CI checks (lint, test, coverage)
    cmds:
      - task: lint
      - task: test
      - task: covercheck

  test:
    summary: Run tests
    deps: [test-version]
    cmd: go test ./... {{.CLI_ARGS}}

  test-version:
    summary: Test that the application version is correctly injected at build time
    cmd: go test -v -tags=integration ./internal
