version: "3"

tasks:
  default:
    deps: [dev]

  dev:
    summary: Development mode
    cmd: go run . {{.CLI_ARGS}}

  build:
    summary: Build application
    cmd: go build -o dist/up .

  clean:
    summary: Clean the project
    cmd: go clean

  devdep:
    summary: Install dev dependencies
    cmds:
      # Linters
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
      # Formatters
      - go install mvdan.cc/gofumpt@latest
      - go install github.com/daixiang0/gci@latest

  fmt:
    summary: Format the code
    cmds:
      - gci write .
      - gofumpt -w .

  tidy:
    summary: Tidy the module
    cmds:
      - go mod tidy -v

  depup:
    summary: Upgrades dependencies
    cmds:
      - go get -d -u -t ./...
      - task tidy

  lint:
    summary: Run linters
    cmds:
      - go vet ./...
      - golangci-lint run ./...
      - staticcheck ./...
      - gosec -fmt=golint -quiet ./...

  test:
    summary: Run tests
    cmd: go test -v ./... {{.CLI_ARGS}}
