version: "3"

vars:
  STATICDIR: internal/static
  HTML: "{{.STATICDIR}}/stats.html"
  MIN: "{{.STATICDIR}}/stats.min.html"
  ISPRESENT: test -x "$(go env GOPATH)/bin"

tasks:
  default:
    deps: [dev]

  dev:
    summary: Development mode
    deps: [minify]
    cmd: go run . {{.CLI_ARGS}}

  minify:
    summary: Minify HTML
    deps: [devdep]
    sources:
      - "{{.HTML}}"
    generates:
      - "{{.MIN}}"
    cmds:
      - minify -o {{.MIN}} {{.HTML}}

  build:
    summary: Build application
    deps: [minify]
    cmd: go build -o dist/upd .

  clean:
    summary: Clean the project
    cmds:
      - go clean
      - rm {{.MIN}}

  devdep:
    summary: Install dev dependencies
    cmds:
      # Minifier
      - go install github.com/tdewolff/minify/v2/cmd/minify@latest
      # Linters
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
      # Formatters
      - go install mvdan.cc/gofumpt@latest
      - go install github.com/daixiang0/gci@latest
    status:
      - "{{.ISPRESENT}}/minify"
      - "{{.ISPRESENT}}/golangci-lint"
      - "{{.ISPRESENT}}/staticcheck"
      - "{{.ISPRESENT}}/gosec"
      - "{{.ISPRESENT}}/gofumpt"
      - "{{.ISPRESENT}}/gci"

  fixlint:
    summary: Fix lint issues
    deps: [devdep]
    cmds:
      - golangci-lint run --fix

  fmt:
    summary: Format the code
    deps: [devdep]
    cmds:
      - gci write .
      - gofumpt -w .

  tidy:
    summary: Tidy the module
    cmds:
      - go mod tidy -v

  depup:
    summary: Upgrades dependencies
    cmds:
      - go get -u -t ./...
      - task tidy

  lint:
    summary: Run linters
    deps: [devdep]
    cmds:
      - go vet ./...
      - golangci-lint run ./...
      - staticcheck ./...
      - gosec -fmt=golint -quiet ./...

  test:
    summary: Run tests
    cmd: go test ./... {{.CLI_ARGS}}
