---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  hk:
    timeout-minutes: 30
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac
      - name: hk checks
        run: hk check --no-progress --profile ci --all
      - name: Display hk log on failure
        if: failure()
        run: cat /home/runner/.local/state/hk/output.log

  versions:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    outputs:
      tools: ${{ steps.mise.outputs.tools }}
    steps:
      - &checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - uses: yshrsmz/action-mise-values@92f49c5a07ebc7ffa957be5efa6a2c673578bbb0
        id: mise

  goci:
    timeout-minutes: 30
    needs: versions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - *checkout
      - &setup-go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version: ${{ fromJson(needs.versions.outputs.tools).go }}
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
      - name: Lint
        run: mise lint
      - name: Test
        run: mise test
      - name: Test Integration
        run: mise test-int
      - name: Coverage
        run: mise covercheck
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build
        run: go build .

  release:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: [hk, versions, goci]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
          fetch-depth: 0
      - *setup-go
      - uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f
        with:
          allow-initial-development-versions: true
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
