---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  hk:
    uses: hugoh/go-tools/.github/workflows/go-hk.yml@bc7c629e60bd78a6b10749054c481382cffedacf # v1.0.0
    permissions:
      contents: read

  goci:
    uses: hugoh/go-tools/.github/workflows/go-ci.yml@bc7c629e60bd78a6b10749054c481382cffedacf # v1.0.0
    permissions:
      contents: read
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: [hk, goci]
    uses: hugoh/go-tools/.github/workflows/go-release.yml@bc7c629e60bd78a6b10749054c481382cffedacf # v1.0.0
    permissions:
      contents: write
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      tap_github_token: ${{ secrets.TAP_GITHUB_TOKEN }}
