---
name: hk

permissions: {}

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  lint:
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number ||
        github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac
      - name: hk checks
        run: hk check --no-progress --all
      - name: Display hk log on failure
        if: failure()
        run: cat /home/runner/.local/state/hk/output.log
