---
name: Update from go-tools template

on:
  schedule:
    - cron: "0 6 * * 1"
  repository_dispatch:
    types: [go-tools-updated]
  workflow_dispatch: {}

permissions: {}

jobs:
  update:
    uses: hugoh/go-tools/.github/workflows/go-template-update.yml@14d0213d60106e5368545ecd27a958dc2afa3b8f
    permissions:
      contents: write
      pull-requests: write
    secrets:
      gh_token: ${{ secrets.TEMPLATE_UPDATE_TOKEN }}
